### ISSUE TITLE
Have fun

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/MCPluginDev.github.io#3]
Here. Take this code and do something with it.

**Comment by foxcqrn** [comment]
<!DOCTYPE html>
<html>
    <head>
        <style type='text/css'>
            body {
                background-image: url("http://s3.amazonaws.com/spoonflower/public/design_thumbnails/0245/9245/mcdirt_shop_preview.png");
            }
            div {
                text-align: center;
            }
            p {
                font-size: 25px; 
                font-family: Times;
                color: white;
            }
            h1 {
                font-size: 40px;
            }
            .boxed {
                border: 1px solid black;
                margin: 100px 1000px 100px 1000px;
                background-color: greenyellow;
            }
        </style>
        <title>MCPluginDev | Home</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>
            <h1>MCPluginDev</h1>
        </div>
        <br><div class="boxed"><p>Welcome to the official MCPluginDev Website</p><br><a href="https://github.com/MCPluginDev"><img src="https://avatars2.githubusercontent.com/u/18744110?v=3&s=200" alt="MCPluginDev Logo" width="300" height="300"></a></div><br>
        <div> 
            <p>MCPluginDev is an organization that mainly develops Java software.</p>
        </div>
    </body>
</html>

**Comment by FoxIshDaBest** [comment]
lol markdown rip
